### ISSUE TITLE
Stale Notebook View when SelectedSpot is changed.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#194]
When we select a detail page for a measurement or Sample, for a particular spot and select a different spot, we see stale Notebook view.

**Comment by jessicagood** [comment]
@sdamaraju I had to remove the code from commit 194cd82c5bf01003bad4161d075b2d5e96cbf103 for setting the Notebook Page to Overview when selectedSpot gets changed. If someone is on the Samples or Measurements Page, for example, and switches Spots we want the same page to remain open (but just have the data for the new Spot show as long as there is a data for the page already open). So this might just need to be handled in a different way.

**Comment by sdamaraju** [comment]
Closing with commit 7ec129efb834a54e55c4779c7807910b40321648

**Comment by jessicagood** [comment]
@sdamaraju I had to change how this was implemented in commit 931ae5b01d8de2f2e556fe75cfc0ec9f81b439b4 because it interfered with the functionality for adding manual measurements. Also more detail pages were added like for 3D Structures and Ig/Met Minerals so now switching the page view back to the appropriate overview page is handled by the detail pages themselves instead of having a dictionary. See the following line for how it is now handled in a useEffect in MeasurementDetail.
https://github.com/StraboSpot/StraboSpot-Mobile/blob/a51a0d8561c7192d26c0a90ec0ed3bd2d11698d8/src/modules/measurements/MeasurementDetail.js#L35
