### ISSUE TITLE
Tags move around the tag  list.  Put newer used ones at top

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#236]
The tags  reorder with the selected on  moved to  bottom.    This can get confusing.

https://user-images.githubusercontent.com/9283127/105618053-d6871d00-5da8-11eb-9fa5-e88215495391.mov

**Comment by jessicagood** [comment]
@sdamaraju This issue not fixed fixed when both @NathanNovak and I tested. The tags are still moving to the bottom in Tag Modal.

**Comment by jessicagood** [comment]
@sdamaraju Still getting movement with the lasted pull request, though it's not as bad

**Comment by sdamaraju** [comment]
The used one will move to the top, that was the expectation right ?

**Comment by jessicagood** [comment]
Right. Maybe what is throwing me off is that if you uncheck a tag it is also moved to the top, just as a checked tag is. I'm thinking it should only go to the top if it's checked. @panamint55 Any thoughts on this?

**Comment by panamint55** [comment]
Right now if you use a tag it moves to the bottom.  If you uncheck I think it moves as well.  If you are in the same unit for a long time, which is common, you always have to scroll to the bottom of the list.  This is annoying.  If you check a tag in the window, do not move it while the window is open.  Just leave the list as it is.  Then you close it.  The next time you open it then the tag goes to the top.  Likewise, if you uncheck a tag, it does not move in the window.  In fact, do not have it resort at all if all you do is unselect a tag.  Unselecting should not do anything to the list.

My thoughts.

Doug

**Comment by jessicagood** [comment]
Update from @panamint55: just alphabetize tags by name for now so nothing moves. @sdamaraju There may be other lists of tags where we want to make sure this is implemented too.

**Comment by sdamaraju** [comment]
@jessicagood @panamint55 
So I just implemented the alphabetic order display every-time.
Here is the catch, for all the list of tags that were created before this fix, the modal looks off the alphabetic order, but any new tag addition, or adding spots to tags or multiple tags to multiple spots, will put the whole bunch in an alphabetic order and it will continue to stay like that from there on. So, the first update of tags, will still move the tags up and down, because the actual sort happens then and then on, the list stays as is for all subsequent transactions.

**Comment by sdamaraju** [comment]
closed with commit 0365451bb4b22f0dc84927657b881f54f5542b0c
