### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#281]
Check tagging via lassoing. It doesn't allow you to add a new tag or close on Save. Same with shortcut tagging.

**Comment by sdamaraju** [comment]
@jessicagood close on shortcut modal cannot be done as we have the last spot created option on that modal. But the same is handled with lassoing tags.
Also the save tags makes sense because for shortcut modal, we create a spot as part of the save logic. Now if we remove save then it gets a bit cumbersome. Its still achievable, but we might have to handle a lot of cases like, 
on the first check of a tag we create the spot, and questions like, do we delete the spot "if all the tags are unchecked etc ?" arise.

Please let me know how you want me to take this forward here.

**Comment by sdamaraju** [comment]
Closing this issue with commit 91ba1aa3c2ca38ffeec491257e2d1503ca9c7f73
