### ISSUE TITLE
Portrait oriented photos get rotated as basemaps

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#298]
When I select "view as basemap" for a photo that is in portrait orientation, it gets rotated 90° (so it's in landscape), then stretched vertically so that the aspect ratio makes it LOOK like it's in portrait, but it's really a vertically stretched landscape photo.

**Comment by NathanNovak** [comment]
@sdamaraju Can you take a look at this please?

**Comment by sdamaraju** [comment]
identified the rootcause and fix. Will discuss and push

**Comment by jessicagood** [comment]
Suggested fix in commit aff7260455b238eadba526d3102b1b4f89f77654 did not work for image basemaps imported from SS1. Reverted this and implemented a different fix with commit 555b87c7082ea81398b6f27724f8c0b84f98e526 (improved from commit 872d5a8fab903bbedb4fc87499a15ff11dc371bb).

Height and width are transposed on portrait images taken with the camera. Running the image through the image resizer fixes this. The intention is not resize the images here though, just fix the rotation.

@sdamaraju Could you test since you were working on this issue initially, especially with SS1?

**Comment by sdamaraju** [comment]
@jessicagood sure Jessica, I will update this thread by eod today.

**Comment by sdamaraju** [comment]
@jessicagood  Tested this, with current image data captured using SS2 and also with image data migrated to SS2 from SS1.

Both work great.

Thanks,
Sai

**Comment by sdamaraju** [comment]
Closing the issue post successful testing
