### ISSUE TITLE
Online/Offline Icon

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#326]
Make it only appear on the map when offline and make it not look like a button.

**Comment by NathanNovak** [comment]
@nicolasmroberts can you get me an icon that does not look like a button?

**Comment by NathanNovak** [comment]
@nicolasmroberts I moved the offline icon to the middle of the Home page and made it only visible when offline. This seems to be a little cleaner.  I think we can actually use the same icon but take a look when I upload a new version to Strabo today. 

I am going to close this issue for now.
fixed with commit 5199fa318e8662362dd000d0f0c8a1588edf03a7
