### ISSUE TITLE
misspelled star icon sidebar headings

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#358]
sidebar that gets pulled up by the star icon. This sidebar the misspelled headings “Slickenliness” and “Striationss”.

**Comment by jessicagood** [comment]
This will be fixed in the next version.  The code was attempting to pluralize the feature types being listed in the Map Symbols list but apparently some features were already pluralized. I removed the pluralization and now the Map Symbols list will show the feature as it is listed in the KoBo forms (Planar, Linear, Tabular Orientations forms). The pluralization consistency in KoBo Forms lists could probably be improved.

Fixed with commit a662025d888ae65df3f98f4d50502b9260c67b13
